---
title: "PHD_Results"
author: "Hannah Coyle"
date: "03/05/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
rmarkdown::render(output_file = "/Analysis/Knitr/PHD_Results.html")
#load necessary libraries
library(tidyverse)
library(knitr)
library(kableExtra)
library(stargazer)
library(psych)
library(here)
```


##Load Data
```{r load_data, echo=FALSE, message=FALSE, warning=FALSE}
here<-"~/Documents/PHD-Data-Analysis/PHD-Data-Analysis"
setwd(here) #main path/homedirectory
#load data (already clean)
setwd("./Analysis/Data")
load("~/Documents/PHD-Data-Analysis/PHD-Data-Analysis/Analysis/Data/COMBINED_COG_PhD.Rdata")
#source('~/Documents/PHD-Data-Analysis/PHD-Data-Analysis/Analysis/Code/data_cleaning.R') #if data not already clean
#exclude participants 
COMBINED_COG_PhD <-subset(COMBINED_COG_PhD,!code %in% c(7, 16))
```

##Check for Missing Data
#```{r missing_data, echo=TRUE}
#check for missing data
#setwd("./Analysis/Code")
#source('missing_data.R')

## haven't got this file up and running yet
#```

# Run exloratory demographics analysis
```{r demographics, echo=TRUE, message=FALSE}
# explore demographics (age, education, sex, wtar) for both groups
setwd(here) #main path/homedirectory
setwd("./Analysis/Code")
source("demographics.R")
print(dem_descriptives) #print demographic descriptives
print (dem_normality) #mtbi age,education and wtar nonormal, control wtar non normal
print (dem_variance) #wtar violates homogeneity of variance assumptions
print (dem_wc_rank) # wilcox rank test (non normal)
print (dem_ttest) # anova (normal)
print(dem_table_nonnorm) # table output (non normal)
print(dem_table_norm) # table output (normal)
  #can possibly include box_plots of descriptives 

#explore characteristics for mTBI group
print(dys_pst_injury) #number of days post injury for each session (BL,T1,T2)
print(dys_pst_injury_sum) #summary stats
print(loc_table) #number of mtbi participants with LOC
print(injury_table) #breakdown of injury types
print(amnesia_table)#breakdown of amnesia types
print(comb_plot) # combined graph of amnesia and injury characteristics
print(pcs_table) # number of mtbi participants with PCS
print(ct_path_table) #number of mtbi participants with ct pathology
print(ct_path_plot) #plot of ct pathology
print(ct_path_type_table) #number of types of ct pathology
print(prior_inj_table) # number of mtbi participants with hx of prior head injury
print(other_inj_table) # number of mtbi participants with concurrent othopaedic/other injury

```

# Run exploratory clinical data analysis
```{r clinical_data, echo=TRUE, message=FALSE}
setwd(here) #main path/homedirectory
setwd("./Analysis/Code")
source("clinical_data.R")
# explore demographics (RPQ, MFI, HADS, SF-36, MFI) for both groups
print(clin_descriptives) #print clinical descriptives
print (clin_normality) # most data non normal (filtered p<.05)
print (clin_variance) # most data violates homogeneity of variance assumptions (filtered p<.05)
print (clin_wc_rank) # wilcox rank test (non normal)
print (clin_ttest) # anova (normal)
print (clin_table_nonnorm)
print (clin_table_norm) 
  #can possibly include box_plots of descriptives 

```

# Run exploratory cognitive data analysis
```{r cognitive_data, echo=FALSE}
# create cognitive data table for both groups
source('~/Documents/PHD-Data-Analysis/PHD-Data-Analysis/Analysis/Code/cognitive_data.R')
print(cog_table)


### TO DO- look at old "Cognitive_data.Rmd" file and copy into new script- then cross map with this Rmd file

# next will be to look at associations between then data & think about what longitudinal analysis will look like. 
```